### ISSUE TITLE
Line ending issue in bin/download-collection.js

### ISSUE THREAD

**Issue by cbabos** [chtefi/download-collection#1]
The file uses DOS line endings which creates an error on OSX.

``` SH
$~  download-collection
env: node\r: No such file or directory
```

Edit: actually the problem only exists in the npm-installed stuff. When I clone it it's okay. Maybe my git client converts the line endings automagically during the `git clone` so I see the correct line endings instead of the npm installed version.

**Comment by sderosiaux** [comment]
Thanks for the info!
Git should have checked in a proper line ending now.

**Comment by cbabos** [comment]
Hey, that was fast! Thank you!  :)
